const GET_IMAGE_LOADING = "GET_IMAGE_LOADING";
const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";
const GET_IMAGE_ERROR = "GET_IMAGE_ERROR";
const FLUSH_IMAGE = "FLUSH_IMAGE";

export default { GET_IMAGE_LOADING, GET_IMAGE_ERROR, GET_IMAGE_SUCCESS, FLUSH_IMAGE };
